// <auto-generated />
using System;
using JobTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobTrack.Api.Migrations
{
    [DbContext(typeof(JobTrackDbContext))]
    [Migration("20260824122907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("JobTrack.Api.Models.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCandidature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePublicationOffre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LienOffre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("JobTrack.Api.Models.CompetenceRequise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("CompetencesRequises");
                });

            modelBuilder.Entity("JobTrack.Api.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LienLinkedIn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("JobTrack.Api.Models.CompetenceRequise", b =>
                {
                    b.HasOne("JobTrack.Api.Models.Candidature", "Candidature")
                        .WithMany("CompetencesRequises")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("JobTrack.Api.Models.Contact", b =>
                {
                    b.HasOne("JobTrack.Api.Models.Candidature", "Candidature")
                        .WithMany("Contacts")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("JobTrack.Api.Models.Candidature", b =>
                {
                    b.Navigation("CompetencesRequises");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
